### PR TITLE
Clearly state that recent version only support Vue 3.x

### PR DESCRIPTION
**Pull request by ameft**
I had to scratch my head a lot before understanding this simple fact, examples didn't help.

### CODE REVIEW

**Comment by LeSuisse** [comment]
Vue 2 is supported with the latest version.

**Comment by ameft** [comment]
Well, if Vue 2 is supported why in the release notes for version 3.0.0 you wrote "[Dropped Vue 2 support](https://github.com/LeSuisse/vue-dompurify-html/releases/tag/v3.0.0)"?
And why if I try to use v4.0.0 in my Nuxt 2.6.3 and Vue 2.7 project I get this Vue3 error?
`ERROR in ./node_modules/vue-dompurify-html/dist/vue-dompurify-html.mjs 4:21
Module parse failed: Unexpected token (4:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { **isVue3** as m } from "vue-demi";
| function p(o, i) {
>   const n = o.hooks ?? {};
|   let t;
|   for (t in n) {`

**Comment by LeSuisse** [comment]
Support was added back in 3.1.0 https://github.com/LeSuisse/vue-dompurify-html/releases/tag/v3.1.0

**Comment by LeSuisse** [comment]
Support of Vue 2 has been dropped, the README now mentions that only Vue 3 is supported.

**Pull request closed without merging**
