### PR TITLE
Allowed for specifying a "default" config.

### PR DESCRIPTION
**Pull request by RohanTalip**

### CODE REVIEW

**Comment by LeSuisse** [comment]
Thanks for your contribution!

I merged it but made a few changes, the directive configuration was not really
made to be extended. Since the change was already a breaking one as someone with
a configuration named "default" could get a completely different behavior before
and after it I preferred to rework the directive configuration to make things a
bit more explicit.

You can now set a default DOMPurify configuration and named ones this way:
```js
Vue.use(VueDOMPurifyHTML, {
  default: { USE_PROFILES: { html: false } },
  namedConfigurations: {
    'svg': {
      USE_PROFILES: { svg: true }
    },
    'mathml': {
      USE_PROFILES: { mathMl: true }
    },
  }
});
```

**Comment by RohanTalip** [comment]
Sounds good.  Thanks.

**Comment by LeSuisse** [comment]
@RohanTalip: Just published as v2.0.0, sorry for the delay!

**Comment by RohanTalip** [comment]
@LeSuisse, no problem.  Thanks for releasing this.

**Pull request merged**
